[Datadog Propagator] Faster ID Conversion
herp-inc/hs-opentelemetry pull request #1
Opened 2022-08-22 00:00 UTC by kakkun61

```
benchmarking newTraceIdFromHeader/new
time                 12.44 ns   (12.03 ns .. 12.95 ns)
                     0.994 R²   (0.991 R² .. 1.000 R²)
mean                 12.19 ns   (12.06 ns .. 12.47 ns)
std dev              607.9 ps   (352.0 ps .. 939.6 ps)
variance introduced by outliers: 74% (severely inflated)

benchmarking newTraceIdFromHeader/old
time                 616.2 ns   (610.6 ns .. 624.3 ns)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 621.2 ns   (615.7 ns .. 628.9 ns)
std dev              21.93 ns   (16.08 ns .. 27.70 ns)
variance introduced by outliers: 51% (severely inflated)

benchmarking newHeaderFromTraceId/new
time                 100.4 ns   (99.75 ns .. 101.3 ns)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 100.4 ns   (99.97 ns .. 101.1 ns)
std dev              1.790 ns   (1.204 ns .. 2.637 ns)
variance introduced by outliers: 23% (moderately inflated)

benchmarking newHeaderFromTraceId/old
time                 175.7 ns   (174.9 ns .. 177.0 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 175.5 ns   (175.1 ns .. 176.2 ns)
std dev              1.902 ns   (1.455 ns .. 2.570 ns)
```

2022-08-22 03:45 UTC, ruicc commented on propagators/datadog/src/OpenTelemetry/Propagator/Datadog/Internal.hs
> +  unsafeDupablePerformIO $
`unsafeDupablePerformIO` が使われてますがこれは安全なんでしょうか？ (NOINLINEとか要らないですかね？)

2022-08-22 03:48 UTC, ruicc commented
quickcheckでテストが書かれてるのは良いですね

2022-08-22 04:05 UTC, kakkun61 commented on propagators/datadog/src/OpenTelemetry/Propagator/Datadog/Internal.hs
> +  unsafeDupablePerformIO $
`ByteString` はイミュータブルで、ここでは read するだけなので大丈夫だと思ってます

2022-08-22 04:49 UTC, ruicc commented on propagators/datadog/src/OpenTelemetry/Propagator/Datadog/Internal.hs
> +  unsafeDupablePerformIO $
ちょっと `unsafeDupablePerformIO` について調べます

2022-08-22 12:28 UTC, ruicc commented on propagators/datadog/src/OpenTelemetry/Propagator/Datadog/Internal.hs
> +  unsafeDupablePerformIO $
`unsafeDupablePerformIO` の挙動がわかる例が作れなかったけど挙動はなんとなくわかった。確かにImmutableのデータから読み出すだけなら複数threadで途中まで走っても問題ないですね。
https://hackage.haskell.org/package/base-4.17.0.0/docs/System-IO-Unsafe.html#v:unsafeDupablePerformIO

2022-08-22 12:28 UTC, ruicc commented on propagators/datadog/src/OpenTelemetry/Propagator/Datadog/Internal.hs
> +    BI.createUptoN 20 writeWord64Ptr -- 20 = length (show (maxBound :: Word64))
ここもWord64に対応するByteStringが作られるだけだから複数threadで走っても問題なしと。

2022-08-22 12:30 UTC, ruicc requested changes

2022-08-22 12:30 UTC, ruicc commented on shell.nix
> +      stylish-haskell
formatterはformoleに統一したいとか。

2022-08-24 01:42 UTC, kakkun61 commented on shell.nix
> +      stylish-haskell
どっちかというと hs-opentelemetry に合わせる方がいいと思うんですが、そっちはフォーマッター使ってないみたいなんですよね

2022-08-24 01:44 UTC, ruicc commented on shell.nix
> +      stylish-haskell
なるほど。まあここは保留で

2022-08-24 01:44 UTC, ruicc approved these changes
LGTM!

2022-08-24 01:45 UTC, merged